version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: ./requirements/nginx/Dockerfile
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wp-volume:/var/www/
    networks:
      - inception
    restart: always

  mariadb:
    build:
      context: .
      dockerfile: ./requirements/mariadb/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_ROOT: ${DB_ROOT}
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    build:
      context: .
      dockerfile: ./requirements/wordpress/Dockerfile
    env_file:
      - .env
    container_name: wordpress
    ports:
      - "9000:9000"
    volumes:
      - wp-volume:/var/www/
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always

volumes:
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/jibot/data/wordpress
  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/jibot/data/mariadb

networks:
  inception:
    driver: bridge
  